# Generated by Django 6.0.2 on 2026-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
